version: '3'

services:
  heytrade:
    container_name: apicontainer
    #    restart: always
    build: .
    ports:
      - "${DOCKER_PORT}:8080"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo/taxdowndb
      - DOCKER=y

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none